### ISSUE TITLE
Version 0.21 is not tagged in the rep

### ISSUE THREAD

**Issue by autarch** [salva/p5-Math-Int128#9]
@salva - how did you do the last release? Running `dzil release` should have done this automatically.

Maybe try running `git push --tags` from your local copy of the repo just in case the tag is there but didn't get pushed for some reason.

**Comment by salva** [comment]
IIRC, the `git push` run by `dzil` failed because I have not configured `github.user` in in `git`.

I have manually pushed the tag now.
